grails-app/domain/historiamedica/Farmacologico.groovy
package historiamedica

/**
 * Farmacologico
 * A domain class describes the data object and it's mapping to the database
 */
class Farmacologico {
String farmacologico
    static belongsTo = [Medicamento]
    static hasMany = [medicamento: Medicamento]
	/* Default (injected) attributes of GORM */
//	Long	id
//	Long	version
	
	/* Automatic timestamping of GORM */
//	Date	dateCreated
//	Date	lastUpdated
	
//	static belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
//	static hasMany		= []	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static mappedBy		= []	// specifies which property should be used in a mapping 
	
    static mapping = {
        medicamentos joinTable:[name:"farmacologico_medicamento", key:"farmacologico_id"]
    }
    
	static constraints = {
		farmacologico blank: false, nullable: false
    }
	String toString(){
  	return farmacologico
	} 	
	
	/*
	 * Methods of the Domain Class
	 */
//	@Override	// Override toString for a nicer / more descriptive UI 
//	public String toString() {
//		return "${name}";
//	}
}

grails-app/controllers/historiamedica/FarmacologicoController.groovy
package historiamedica

import org.springframework.dao.DataIntegrityViolationException

/**
 * FarmacologicoController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class FarmacologicoController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [farmacologicoInstanceList: Farmacologico.list(params), farmacologicoInstanceTotal: Farmacologico.count()]
    }

    def create() {
        [farmacologicoInstance: new Farmacologico(params)]
    }

    def save() {
        def farmacologicoInstance = new Farmacologico(params)
        if (!farmacologicoInstance.save(flush: true)) {
            render(view: "create", model: [farmacologicoInstance: farmacologicoInstance])
            return
        }

		flash.message = message(code: 'default.created.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), farmacologicoInstance.id])
        redirect(action: "show", id: farmacologicoInstance.id)
    }

    def show() {
        def farmacologicoInstance = Farmacologico.get(params.id)
        if (!farmacologicoInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), params.id])
            redirect(action: "list")
            return
        }

        [farmacologicoInstance: farmacologicoInstance]
    }

    def edit() {
        def farmacologicoInstance = Farmacologico.get(params.id)
        if (!farmacologicoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), params.id])
            redirect(action: "list")
            return
        }

        [farmacologicoInstance: farmacologicoInstance]
    }

    def update() {
        def farmacologicoInstance = Farmacologico.get(params.id)
        if (!farmacologicoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (farmacologicoInstance.version > version) {
                farmacologicoInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'farmacologico.label', default: 'Farmacologico')] as Object[],
                          "Another user has updated this Farmacologico while you were editing")
                render(view: "edit", model: [farmacologicoInstance: farmacologicoInstance])
                return
            }
        }

        farmacologicoInstance.properties = params

        if (!farmacologicoInstance.save(flush: true)) {
            render(view: "edit", model: [farmacologicoInstance: farmacologicoInstance])
            return
        }

		flash.message = message(code: 'default.updated.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), farmacologicoInstance.id])
        redirect(action: "show", id: farmacologicoInstance.id)
    }

    def delete() {
        def farmacologicoInstance = Farmacologico.get(params.id)
        if (!farmacologicoInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), params.id])
            redirect(action: "list")
            return
        }

        try {
            farmacologicoInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'farmacologico.label', default: 'Farmacologico'), params.id])
            redirect(action: "show", id: params.id)
        }
    }

    def initialLoad() {
        def dir = new File('web-app/f_resources/Farm_List.csv')
        dir.toCsvReader(['skipLines': '1']).eachLine { line ->
            if(line.length==1){
                def farmInstance = new Farmacologico()
                farmInstance.farmacologico=line[0]
                // println labInstance
                if(!farmInstance.save(flush: true)){
                    println "fallo en ${farmInstance.farmacologico}"
                }
            }
        }
        redirect(action: "list")
    }
}

grails-app/views/farmacologico/_form.gsp
<%@ page import="historiamedica.Farmacologico" %>



			<div class="control-group fieldcontain ${hasErrors(bean: farmacologicoInstance, field: 'farmacologico', 'error')} required">
				<label for="farmacologico" class="control-label"><g:message code="farmacologico.farmacologico.label" default="Farmacologico" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:textField name="farmacologico" required="" value="${farmacologicoInstance?.farmacologico}"/>
					<span class="help-inline">${hasErrors(bean: farmacologicoInstance, field: 'farmacologico', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: farmacologicoInstance, field: 'medicamento', 'error')} ">
				<label for="medicamento" class="control-label"><g:message code="farmacologico.medicamento.label" default="Medicamento" /></label>
				<div class="controls">
					
					<span class="help-inline">${hasErrors(bean: farmacologicoInstance, field: 'medicamento', 'error')}</span>
				</div>
			</div>

grails-app/views/farmacologico/create.gsp
<%@ page import="historiamedica.Farmacologico" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'farmacologico.label', default: 'Farmacologico')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="create-farmacologico" class="first">

	<g:hasErrors bean="${farmacologicoInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${farmacologicoInstance}" as="list" />
	</div>
	</g:hasErrors>
	
	<g:form action="save" class="form-horizontal" >
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>
	
</section>
		
</body>

</html>

grails-app/views/farmacologico/edit.gsp
<%@ page import="historiamedica.Farmacologico" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'farmacologico.label', default: 'Farmacologico')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="edit-farmacologico" class="first">

	<g:hasErrors bean="${farmacologicoInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${farmacologicoInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${farmacologicoInstance?.id}" />
		<g:hiddenField name="version" value="${farmacologicoInstance?.version}" />
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
			<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>

</section>
			
</body>

</html>

grails-app/views/farmacologico/index.gsp
<%@ page import="historiamedica.Farmacologico" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'farmacologico.label', default: 'Farmacologico')}" />
	<title><g:message code="default.index.label" args="[entityName]" /></title>
</head>

<body>

<section id="index-farmacologico" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
			<tr>
			
				<g:sortableColumn property="farmacologico" title="${message(code: 'farmacologico.farmacologico.label', default: 'Farmacologico')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${farmacologicoInstanceList}" status="i" var="farmacologicoInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${farmacologicoInstance.id}">${fieldValue(bean: farmacologicoInstance, field: "farmacologico")}</g:link></td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div>
		<bs:paginate total="${farmacologicoInstanceCount}" />
	</div>
</section>

</body>

</html>

grails-app/views/farmacologico/list.gsp
<%@ page import="historiamedica.Farmacologico" %>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'farmacologico.label', default: 'Farmacologico')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="list-farmacologico" class="first">

	<table class="table table-bordered">
		<thead>
			<tr>
			
				<g:sortableColumn property="farmacologico" title="${message(code: 'farmacologico.farmacologico.label', default: 'Farmacologico')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${farmacologicoInstanceList}" status="i" var="farmacologicoInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${farmacologicoInstance.id}">${fieldValue(bean: farmacologicoInstance, field: "farmacologico")}</g:link></td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<bs:paginate total="${farmacologicoInstanceTotal}" />
	</div>
</section>

</body>

</html>

grails-app/views/farmacologico/show.gsp
<%@ page import="historiamedica.Farmacologico" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'farmacologico.label', default: 'Farmacologico')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="show-farmacologico" class="first">

	<table class="table">
		<tbody>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="farmacologico.farmacologico.label" default="Farmacologico" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: farmacologicoInstance, field: "farmacologico")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="farmacologico.medicamento.label" default="Medicamento" /></td>
				
				<td valign="top" style="text-align: left;" class="value">
					<ul>
					<g:each in="${farmacologicoInstance.medicamento}" var="m">
						<li><g:link controller="medicamento" action="show" id="${m.id}">${m?.encodeAsHTML()}</g:link></li>
					</g:each>
					</ul>
				</td>
				
			</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>