grails-app/domain/historiamedica/Typeconsultation.groovy
package historiamedica

/**
 * Typeconsultation
 * A domain class describes the data object and it's mapping to the database
 */
class Typeconsultation {
//static hasMany   = [medico:Medico] 
String code	
String name
	/* Default (injected) attributes of GORM */
//	Long	id
//	Long	version
	
	/* Automatic timestamping of GORM */
//	Date	dateCreated
//	Date	lastUpdated
	
//	static	belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static	hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
//	static	hasMany		= []	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static	mappedBy	= []	// specifies which property should be used in a mapping 
	
    static	mapping = {
    }
    
	static	constraints = {
		code blank: false, nullable: false
		name blank: false, nullable: false
    }
	String toString(){
    return name
   } 	
	/*
	 * Methods of the Domain Class
	 */
//	@Override	// Override toString for a nicer / more descriptive UI 
//	public String toString() {
//		return "${name}";
//	}
}

grails-app/controllers/historiamedica/TypeconsultationController.groovy
package historiamedica

import org.springframework.dao.DataIntegrityViolationException

/**
 * TypeconsultationController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class TypeconsultationController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [typeconsultationInstanceList: Typeconsultation.list(params), typeconsultationInstanceTotal: Typeconsultation.count()]
    }

    def create() {
        [typeconsultationInstance: new Typeconsultation(params)]
    }

    def save() {
        def typeconsultationInstance = new Typeconsultation(params)
        if (!typeconsultationInstance.save(flush: true)) {
            render(view: "create", model: [typeconsultationInstance: typeconsultationInstance])
            return
        }

		flash.message = message(code: 'default.created.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), typeconsultationInstance.id])
        redirect(action: "show", id: typeconsultationInstance.id)
    }

    def show() {
        def typeconsultationInstance = Typeconsultation.get(params.id)
        if (!typeconsultationInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), params.id])
            redirect(action: "list")
            return
        }

        [typeconsultationInstance: typeconsultationInstance]
    }

    def edit() {
        def typeconsultationInstance = Typeconsultation.get(params.id)
        if (!typeconsultationInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), params.id])
            redirect(action: "list")
            return
        }

        [typeconsultationInstance: typeconsultationInstance]
    }

    def update() {
        def typeconsultationInstance = Typeconsultation.get(params.id)
        if (!typeconsultationInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (typeconsultationInstance.version > version) {
                typeconsultationInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'typeconsultation.label', default: 'Typeconsultation')] as Object[],
                          "Another user has updated this Typeconsultation while you were editing")
                render(view: "edit", model: [typeconsultationInstance: typeconsultationInstance])
                return
            }
        }

        typeconsultationInstance.properties = params

        if (!typeconsultationInstance.save(flush: true)) {
            render(view: "edit", model: [typeconsultationInstance: typeconsultationInstance])
            return
        }

		flash.message = message(code: 'default.updated.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), typeconsultationInstance.id])
        redirect(action: "show", id: typeconsultationInstance.id)
    }

    def delete() {
        def typeconsultationInstance = Typeconsultation.get(params.id)
        if (!typeconsultationInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), params.id])
            redirect(action: "list")
            return
        }

        try {
            typeconsultationInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'typeconsultation.label', default: 'Typeconsultation'), params.id])
            redirect(action: "show", id: params.id)
        }
    }
}

grails-app/views/typeconsultation/_form.gsp
<%@ page import="historiamedica.Typeconsultation" %>



			<div class="control-group fieldcontain ${hasErrors(bean: typeconsultationInstance, field: 'code', 'error')} required">
				<label for="code" class="control-label"><g:message code="typeconsultation.code.label" default="Code" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:textField name="code" required="" value="${typeconsultationInstance?.code}"/>
					<span class="help-inline">${hasErrors(bean: typeconsultationInstance, field: 'code', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: typeconsultationInstance, field: 'name', 'error')} required">
				<label for="name" class="control-label"><g:message code="typeconsultation.name.label" default="Name" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:textField name="name" required="" value="${typeconsultationInstance?.name}"/>
					<span class="help-inline">${hasErrors(bean: typeconsultationInstance, field: 'name', 'error')}</span>
				</div>
			</div>

grails-app/views/typeconsultation/create.gsp
<%@ page import="historiamedica.Typeconsultation" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'typeconsultation.label', default: 'Typeconsultation')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

		<g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />
		
		<li class="${ params.action == "list" ? 'active' : '' }">
			<g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
		</li>
		<li class="${ params.action == "create" ? 'active' : '' }">
			<g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
		</li>
		
		<g:if test="${ params.action == 'show' || params.action == 'edit' }">
			<!-- the item is an object (not a list) -->
			<li class="${ params.action == "edit" ? 'active' : '' }">
				<g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
			</li>
			<li class="">
				<g:render template="/_common/modals/deleteTextLink"/>
			</li>
		</g:if>
		
	</ul>
<section id="create-typeconsultation" class="first">

	<g:hasErrors bean="${typeconsultationInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${typeconsultationInstance}" as="list" />
	</div>
	</g:hasErrors>
	
	<g:form action="save" class="form-horizontal" >
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>
	
</section>
		
</body>

</html>

grails-app/views/typeconsultation/edit.gsp
<%@ page import="historiamedica.Typeconsultation" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'typeconsultation.label', default: 'Typeconsultation')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

		<g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />
		
		<li class="${ params.action == "list" ? 'active' : '' }">
			<g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
		</li>
		<li class="${ params.action == "create" ? 'active' : '' }">
			<g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
		</li>
		
		<g:if test="${ params.action == 'show' || params.action == 'edit' }">
			<!-- the item is an object (not a list) -->
			<li class="${ params.action == "edit" ? 'active' : '' }">
				<g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
			</li>
			<li class="">
				<g:render template="/_common/modals/deleteTextLink"/>
			</li>
		</g:if>
		
	</ul>
<section id="edit-typeconsultation" class="first">

	<g:hasErrors bean="${typeconsultationInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${typeconsultationInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${typeconsultationInstance?.id}" />
		<g:hiddenField name="version" value="${typeconsultationInstance?.version}" />
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
			<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>

</section>
			
</body>

</html>

grails-app/views/typeconsultation/index.gsp
<%@ page import="historiamedica.Typeconsultation" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'typeconsultation.label', default: 'Typeconsultation')}" />
	<title><g:message code="default.index.label" args="[entityName]" /></title>
</head>

<body>

<section id="index-typeconsultation" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
			<tr>
			
				<g:sortableColumn property="code" title="${message(code: 'typeconsultation.code.label', default: 'Code')}" />
			
				<g:sortableColumn property="name" title="${message(code: 'typeconsultation.name.label', default: 'Name')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${typeconsultationInstanceList}" status="i" var="typeconsultationInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${typeconsultationInstance.id}">${fieldValue(bean: typeconsultationInstance, field: "code")}</g:link></td>
			
				<td>${fieldValue(bean: typeconsultationInstance, field: "name")}</td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div>
		<bs:paginate total="${typeconsultationInstanceCount}" />
	</div>
</section>

</body>

</html>

grails-app/views/typeconsultation/list.gsp
<%@ page import="historiamedica.Typeconsultation" %>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'typeconsultation.label', default: 'Typeconsultation')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

		<g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />
		
		<li class="${ params.action == "list" ? 'active' : '' }">
			<g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
		</li>
		<li class="${ params.action == "create" ? 'active' : '' }">
			<g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
		</li>
		
		<g:if test="${ params.action == 'show' || params.action == 'edit' }">
			<!-- the item is an object (not a list) -->
			<li class="${ params.action == "edit" ? 'active' : '' }">
				<g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
			</li>
			<li class="">
				<g:render template="/_common/modals/deleteTextLink"/>
			</li>
		</g:if>
		
	</ul>	
<section id="list-typeconsultation" class="first">

	<table class="table table-bordered">
		<thead>
			<tr>
			
				<g:sortableColumn property="code" title="${message(code: 'typeconsultation.code.label', default: 'Code')}" />
			
				<g:sortableColumn property="name" title="${message(code: 'typeconsultation.name.label', default: 'Name')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${typeconsultationInstanceList}" status="i" var="typeconsultationInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${typeconsultationInstance.id}">${fieldValue(bean: typeconsultationInstance, field: "code")}</g:link></td>
			
				<td>${fieldValue(bean: typeconsultationInstance, field: "name")}</td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<bs:paginate total="${typeconsultationInstanceTotal}" />
	</div>
</section>

</body>

</html>

grails-app/views/typeconsultation/show.gsp
<%@ page import="historiamedica.Typeconsultation" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'typeconsultation.label', default: 'Typeconsultation')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

		<g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />
		
		<li class="${ params.action == "list" ? 'active' : '' }">
			<g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
		</li>
		<li class="${ params.action == "create" ? 'active' : '' }">
			<g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
		</li>
		
		<g:if test="${ params.action == 'show' || params.action == 'edit' }">
			<!-- the item is an object (not a list) -->
			<li class="${ params.action == "edit" ? 'active' : '' }">
				<g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
			</li>
			<li class="">
				<g:render template="/_common/modals/deleteTextLink"/>
			</li>
		</g:if>
		
	</ul>
<section id="show-typeconsultation" class="first">

	<table class="table">
		<tbody>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="typeconsultation.code.label" default="Code" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: typeconsultationInstance, field: "code")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="typeconsultation.name.label" default="Name" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: typeconsultationInstance, field: "name")}</td>
				
			</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>