grails-app/domain/historiamedica/Usuario.groovy
package historiamedica

class Usuario {

	transient springSecurityService

	String username
	String password
    String email
	boolean enabled
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
    static hasMany = [rol:Rol]

	static constraints = {
		username blank: false, unique: true
		password blank: false
        email    blank: false, email: true
	}

	static mapping = {
        rols joinTable:[name:"usario_rol", key:"usuario_id"]
		password column: '`password`'
	}

	Set<Rol> getAuthorities() {
		UsuarioRol.findAllByUsuario(this).collect { it.rol } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}
}

grails-app/controllers/historiamedica/UsuarioController.groovy
package historiamedica

import org.springframework.dao.DataIntegrityViolationException

/**
 * UsuarioController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class UsuarioController {
    def springSecurityService
    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [usuarioInstanceList: Usuario.list(params), usuarioInstanceTotal: Usuario.count()]
    }

    def create() {
        [usuarioInstance: new Usuario(params)]
    }

    def save() {
        def usuarioInstance = new Usuario(params)
        if (!usuarioInstance.save(flush: true)) {
            render(view: "create", model: [usuarioInstance: usuarioInstance])
            return
        }

		flash.message = message(code: 'default.created.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuarioInstance.id])
        redirect(action: "show", id: usuarioInstance.username.encodeAsBase64())
    }

    def show() {
        def usuarioInstance = Usuario.findByUsername(new String(params.id.decodeBase64()))
        if (!usuarioInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
            redirect(action: "list")
            return
        }

        [usuarioInstance: usuarioInstance]
    }

    def edit() {
        def usuarioInstance = Usuario.findByUsername(new String(params.id.decodeBase64()))
        if (!usuarioInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.username])
            redirect(action: "list")
            return
        }

        [usuarioInstance: usuarioInstance]
    }

    def editprofile() {
        if(springSecurityService.isLoggedIn()) {
            def user=springSecurityService.getCurrentUser()
            println user.getAt('id')
            def usuarioInstance = Usuario.get(user.getAt('id'))
            if (usuarioInstance) {
                println "entro correctamente"
                render(view: "edit", model: [usuarioInstance: usuarioInstance])
                return
            }
            else {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), user.getAt('id')])
                redirect(controller: "Home", action: "index")
            }
        }
    }

    def update() {
        def usuarioInstance = Usuario.findByUsername(new String(params.id.decodeBase64()))
        if (!usuarioInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (usuarioInstance.version > version) {
                usuarioInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'usuario.label', default: 'Usuario')] as Object[],
                          "Another user has updated this Usuario while you were editing")
                render(view: "edit", model: [usuarioInstance: usuarioInstance])
                return
            }
        }

        usuarioInstance.properties = params
        println "entro a alguna cosa aqui"
        if (!usuarioInstance.save(flush: true)) {
            usuarioInstance.id=usuarioInstance.username.encodeAsBase64()
            render(view: "edit", model: [usuarioInstance: usuarioInstance])
            return
        }

		flash.message = message(code: 'default.updated.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuarioInstance.id])
        redirect(action: "show", id: usuarioInstance.username.encodeAsBase64())
    }

    def delete() {
        def usuarioInstance = Usuario.get(params.id)
        if (!usuarioInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
            redirect(action: "list")
            return
        }

        try {
            usuarioInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
            redirect(action: "show", id: params.id)
        }
    }
}

grails-app/views/usuario/_form.gsp
<%@ page import="historiamedica.Usuario" %>



			<div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'username', 'error')} required">
				<label for="username" class="control-label"><g:message code="usuario.username.label" default="Username" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<sec:ifAnyGranted roles="ROLE_ADMIN">
					    <g:textField name="username" required="" value="${usuarioInstance?.username}"/>
					    <span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'username', 'error')}</span>
                    </sec:ifAnyGranted>
                    <sec:ifNotGranted roles="ROLE_ADMIN">
                        ${usuarioInstance?.username}
                    </sec:ifNotGranted>
				</div>
			</div>

            <div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'password', 'error')} required">
				<label for="password" class="control-label"><g:message code="usuario.password.label" default="Password" /><span class="required-indicator">*</span></label>
				<div class="controls">
                        <g:textField name="password" required="" value="" />
					    <span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'password', 'error')}</span>
				</div>
			</div>


			<div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'email', 'error')} required">
				<label for="email" class="control-label"><g:message code="usuario.email.label" default="Email" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:field type="email" name="email" required="" value="${usuarioInstance?.email}"/>
					<span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'email', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'accountExpired', 'error')} ">
				<label for="accountExpired" class="control-label"><g:message code="usuario.accountExpired.label" default="Account Expired" /></label>
				<div class="controls">
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <bs:checkBox name="accountExpired" value="${usuarioInstance?.accountExpired}" />
					    <span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'accountExpired', 'error')}</span>
                    </sec:ifAnyGranted>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'accountLocked', 'error')} ">
				<label for="accountLocked" class="control-label"><g:message code="usuario.accountLocked.label" default="Account Locked" /></label>
				<div class="controls">
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <bs:checkBox name="accountLocked" value="${usuarioInstance?.accountLocked}" />
					    <span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'accountLocked', 'error')}</span>
                    </sec:ifAnyGranted>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'enabled', 'error')} ">
				<label for="enabled" class="control-label"><g:message code="usuario.enabled.label" default="Enabled" /></label>
				<div class="controls">
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <bs:checkBox name="enabled" value="${usuarioInstance?.enabled}" />
                        <span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'enabled', 'error')}</span>
                    </sec:ifAnyGranted>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'passwordExpired', 'error')} ">
				<label for="passwordExpired" class="control-label"><g:message code="usuario.passwordExpired.label" default="Password Expired" /></label>
				<div class="controls">
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <bs:checkBox name="passwordExpired" value="${usuarioInstance?.passwordExpired}" />
                        <span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'passwordExpired', 'error')}</span>
                    </sec:ifAnyGranted>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: usuarioInstance, field: 'rol', 'error')} ">
				<label for="rol" class="control-label"><g:message code="usuario.rol.label" default="Rol" /></label>
				<div class="controls">
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
					    <g:select name="rol" from="${historiamedica.Rol.list()}" multiple="multiple" optionKey="id" size="5" value="${usuarioInstance?.rol*.id}" class="many-to-many"/>
                    </sec:ifAnyGranted>
                    <sec:ifNotGranted roles="ROLE_ADMIN">
                        <ul>
                            <g:each in="${usuarioInstance.rol}" var="r">
                                <li>${r?.encodeAsHTML()}</li>
                            </g:each>
                        </ul>
                        <%--<g:select name="rol" from="${historiamedica.Rol.list()}" multiple="multiple" optionKey="id" size="5" value="${usuarioInstance?.rol*.id}" class="many-to-many" readonly="true"/>--%>
                    </sec:ifNotGranted>
					<span class="help-inline">${hasErrors(bean: usuarioInstance, field: 'rol', 'error')}</span>
				</div>
			</div>

grails-app/views/usuario/create.gsp
<%@ page import="historiamedica.Usuario" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="create-usuario" class="first">

	<g:hasErrors bean="${usuarioInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${usuarioInstance}" as="list" />
	</div>
	</g:hasErrors>
	
	<g:form action="save" class="form-horizontal" >
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>
	
</section>
		
</body>

</html>

grails-app/views/usuario/edit.gsp
<%@ page import="historiamedica.Usuario" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>
<sec:ifAnyGranted roles="ROLE_ADMIN">
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
</sec:ifAnyGranted>
<section id="edit-usuario" class="first">

	<g:hasErrors bean="${usuarioInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${usuarioInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${usuarioInstance?.username.encodeAsBase64()}" />
		<g:hiddenField name="version" value="${usuarioInstance?.version}" />
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
			<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>

</section>
			
</body>

</html>

grails-app/views/usuario/index.gsp
<%@ page import="historiamedica.Usuario" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
	<title><g:message code="default.index.label" args="[entityName]" /></title>
</head>

<body>

<section id="index-usuario" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
			<tr>
			
				<g:sortableColumn property="username" title="${message(code: 'usuario.username.label', default: 'Username')}" />
			
				<g:sortableColumn property="password" title="${message(code: 'usuario.password.label', default: 'Password')}" />
			
				<g:sortableColumn property="email" title="${message(code: 'usuario.email.label', default: 'Email')}" />
			
				<g:sortableColumn property="accountExpired" title="${message(code: 'usuario.accountExpired.label', default: 'Account Expired')}" />
			
				<g:sortableColumn property="accountLocked" title="${message(code: 'usuario.accountLocked.label', default: 'Account Locked')}" />
			
				<g:sortableColumn property="enabled" title="${message(code: 'usuario.enabled.label', default: 'Enabled')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${usuarioInstanceList}" status="i" var="usuarioInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${usuarioInstance.id}">${fieldValue(bean: usuarioInstance, field: "username")}</g:link></td>
			
				<td>${fieldValue(bean: usuarioInstance, field: "password")}</td>
			
				<td>${fieldValue(bean: usuarioInstance, field: "email")}</td>
			
				<td><g:formatBoolean boolean="${usuarioInstance.accountExpired}" /></td>
			
				<td><g:formatBoolean boolean="${usuarioInstance.accountLocked}" /></td>
			
				<td><g:formatBoolean boolean="${usuarioInstance.enabled}" /></td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div>
		<bs:paginate total="${usuarioInstanceCount}" />
	</div>
</section>

</body>

</html>

grails-app/views/usuario/list.gsp
<%@ page import="historiamedica.Usuario" %>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="list-usuario" class="first">

	<table class="table table-bordered">
		<thead>
			<tr>
			
				<g:sortableColumn property="username" title="${message(code: 'usuario.username.label', default: 'Username')}" />
			
				<%--<g:sortableColumn property="password" title="${message(code: 'usuario.password.label', default: 'Password')}" />--%>
			
				<g:sortableColumn property="email" title="${message(code: 'usuario.email.label', default: 'Email')}" />
			
				<g:sortableColumn property="accountExpired" title="${message(code: 'usuario.accountExpired.label', default: 'Account Expired')}" />
			
				<g:sortableColumn property="accountLocked" title="${message(code: 'usuario.accountLocked.label', default: 'Account Locked')}" />
			
				<g:sortableColumn property="enabled" title="${message(code: 'usuario.enabled.label', default: 'Enabled')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${usuarioInstanceList}" status="i" var="usuarioInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${usuarioInstance.username.encodeAsBase64()}">${fieldValue(bean: usuarioInstance, field: "username")}</g:link></td>
			
				<%--<td>${fieldValue(bean: usuarioInstance, field: "password")}</td>--%>
				<%--<td>${fieldValue(bean: usuarioInstance, field: "password")}</td>--%>

				<td>${fieldValue(bean: usuarioInstance, field: "email")}</td>
			
				<td><g:formatBoolean boolean="${usuarioInstance.accountExpired}" /></td>
			
				<td><g:formatBoolean boolean="${usuarioInstance.accountLocked}" /></td>
			
				<td><g:formatBoolean boolean="${usuarioInstance.enabled}" /></td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<bs:paginate total="${usuarioInstanceTotal}" />
	</div>
</section>

</body>

</html>

grails-app/views/usuario/show.gsp
<%@ page import="historiamedica.Usuario" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="show-usuario" class="first">

	<table class="table">
		<tbody>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.username.label" default="Username" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: usuarioInstance, field: "username")}</td>
				
			</tr>
		
			<%--<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.password.label" default="Password" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: usuarioInstance, field: "password")}</td>
				
			</tr>--%>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.email.label" default="Email" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: usuarioInstance, field: "email")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.accountExpired.label" default="Account Expired" /></td>
				
				<td valign="top" class="value"><g:formatBoolean boolean="${usuarioInstance?.accountExpired}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.accountLocked.label" default="Account Locked" /></td>
				
				<td valign="top" class="value"><g:formatBoolean boolean="${usuarioInstance?.accountLocked}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.enabled.label" default="Enabled" /></td>
				
				<td valign="top" class="value"><g:formatBoolean boolean="${usuarioInstance?.enabled}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.passwordExpired.label" default="Password Expired" /></td>
				
				<td valign="top" class="value"><g:formatBoolean boolean="${usuarioInstance?.passwordExpired}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="usuario.rol.label" default="Rol" /></td>
				
				<td valign="top" style="text-align: left;" class="value">
					<ul>
					<g:each in="${usuarioInstance.rol}" var="r">
						<li>${r?.encodeAsHTML()}</li>
					</g:each>
					</ul>
				</td>
				
			</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>