grails-app/domain/historiamedica/Principio.groovy
package historiamedica

/**
 * Principio
 * A domain class describes the data object and it's mapping to the database
 */
class Principio {
String principio
    static belongsTo = [Medicamento]
    static hasMany = [medicamento: Medicamento]
	/* Default (injected) attributes of GORM */
//	Long	id
//	Long	version
	
	/* Automatic timestamping of GORM */
//	Date	dateCreated
//	Date	lastUpdated
	
//	static belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
//	static hasMany		= []	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static mappedBy		= []	// specifies which property should be used in a mapping 
	
    static mapping = {
        medicamentos joinTable:[name:"principio_medicamento", key:"principio_id"]
    }
    
	static constraints = {

    principio blank: false, nullable: false
    }
	String toString(){
  	return principio
	} 	
	/*
	 * Methods of the Domain Class
	 */
//	@Override	// Override toString for a nicer / more descriptive UI 
//	public String toString() {
//		return "${name}";
//	}
}

grails-app/controllers/historiamedica/PrincipioController.groovy
package historiamedica

import org.springframework.dao.DataIntegrityViolationException

/**
 * PrincipioController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class PrincipioController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [principioInstanceList: Principio.list(params), principioInstanceTotal: Principio.count()]
    }

    def create() {
        [principioInstance: new Principio(params)]
    }

    def save() {
        def principioInstance = new Principio(params)
        if (!principioInstance.save(flush: true)) {
            render(view: "create", model: [principioInstance: principioInstance])
            return
        }

		flash.message = message(code: 'default.created.message', args: [message(code: 'principio.label', default: 'Principio'), principioInstance.id])
        redirect(action: "show", id: principioInstance.id)
    }

    def show() {
        def principioInstance = Principio.get(params.id)
        if (!principioInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'principio.label', default: 'Principio'), params.id])
            redirect(action: "list")
            return
        }

        [principioInstance: principioInstance]
    }

    def edit() {
        def principioInstance = Principio.get(params.id)
        if (!principioInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'principio.label', default: 'Principio'), params.id])
            redirect(action: "list")
            return
        }

        [principioInstance: principioInstance]
    }

    def update() {
        def principioInstance = Principio.get(params.id)
        if (!principioInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'principio.label', default: 'Principio'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (principioInstance.version > version) {
                principioInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'principio.label', default: 'Principio')] as Object[],
                          "Another user has updated this Principio while you were editing")
                render(view: "edit", model: [principioInstance: principioInstance])
                return
            }
        }

        principioInstance.properties = params

        if (!principioInstance.save(flush: true)) {
            render(view: "edit", model: [principioInstance: principioInstance])
            return
        }

		flash.message = message(code: 'default.updated.message', args: [message(code: 'principio.label', default: 'Principio'), principioInstance.id])
        redirect(action: "show", id: principioInstance.id)
    }

    def delete() {
        def principioInstance = Principio.get(params.id)
        if (!principioInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'principio.label', default: 'Principio'), params.id])
            redirect(action: "list")
            return
        }

        try {
            principioInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'principio.label', default: 'Principio'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'principio.label', default: 'Principio'), params.id])
            redirect(action: "show", id: params.id)
        }
    }

    def initialLoad() {
        def dir = new File('web-app/f_resources/Prin_List.csv')
        dir.toCsvReader(['skipLines': '1']).eachLine { line ->
            if(line.length==1){
                def prinInstance = new Principio()
                prinInstance.principio=line[0]
                // println labInstance
                if(!prinInstance.save(flush: true)){
                    println "fallo en ${prinInstance.principio}"
                }
            }
        }
        redirect(action: "list")
    }
}

grails-app/views/principio/_form.gsp
<%@ page import="historiamedica.Principio" %>



			<div class="control-group fieldcontain ${hasErrors(bean: principioInstance, field: 'principio', 'error')} required">
				<label for="principio" class="control-label"><g:message code="principio.principio.label" default="Principio" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:textField name="principio" required="" value="${principioInstance?.principio}"/>
					<span class="help-inline">${hasErrors(bean: principioInstance, field: 'principio', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: principioInstance, field: 'medicamento', 'error')} ">
				<label for="medicamento" class="control-label"><g:message code="principio.medicamento.label" default="Medicamento" /></label>
				<div class="controls">
					
					<span class="help-inline">${hasErrors(bean: principioInstance, field: 'medicamento', 'error')}</span>
				</div>
			</div>

grails-app/views/principio/create.gsp
<%@ page import="historiamedica.Principio" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'principio.label', default: 'Principio')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="create-principio" class="first">

	<g:hasErrors bean="${principioInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${principioInstance}" as="list" />
	</div>
	</g:hasErrors>
	
	<g:form action="save" class="form-horizontal" >
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>
	
</section>
		
</body>

</html>

grails-app/views/principio/edit.gsp
<%@ page import="historiamedica.Principio" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'principio.label', default: 'Principio')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="edit-principio" class="first">

	<g:hasErrors bean="${principioInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${principioInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${principioInstance?.id}" />
		<g:hiddenField name="version" value="${principioInstance?.version}" />
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
			<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            <button class="btn" type="reset">Cancel</button>
		</div>
	</g:form>

</section>
			
</body>

</html>

grails-app/views/principio/index.gsp
<%@ page import="historiamedica.Principio" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'principio.label', default: 'Principio')}" />
	<title><g:message code="default.index.label" args="[entityName]" /></title>
</head>

<body>

<section id="index-principio" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
			<tr>
			
				<g:sortableColumn property="principio" title="${message(code: 'principio.principio.label', default: 'Principio')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${principioInstanceList}" status="i" var="principioInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${principioInstance.id}">${fieldValue(bean: principioInstance, field: "principio")}</g:link></td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div>
		<bs:paginate total="${principioInstanceCount}" />
	</div>
</section>

</body>

</html>

grails-app/views/principio/list.gsp
<%@ page import="historiamedica.Principio" %>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'principio.label', default: 'Principio')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="list-principio" class="first">

	<table class="table table-bordered">
		<thead>
			<tr>
			
				<g:sortableColumn property="principio" title="${message(code: 'principio.principio.label', default: 'Principio')}" />
			
			</tr>
		</thead>
		<tbody>
		<g:each in="${principioInstanceList}" status="i" var="principioInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			
				<td><g:link action="show" id="${principioInstance.id}">${fieldValue(bean: principioInstance, field: "principio")}</g:link></td>
			
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<bs:paginate total="${principioInstanceTotal}" />
	</div>
</section>

</body>

</html>

grails-app/views/principio/show.gsp
<%@ page import="historiamedica.Principio" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'principio.label', default: 'Principio')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
<ul id="Menu" class="nav nav-pills">

    <g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

    <li class="${ params.action == "list" ? 'active' : '' }">
        <g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
    </li>
    <li class="${ params.action == "create" ? 'active' : '' }">
        <g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
    </li>

    <g:if test="${ params.action == 'show' || params.action == 'edit' }">
        <!-- the item is an object (not a list) -->
        <li class="${ params.action == "edit" ? 'active' : '' }">
            <g:link action="edit" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
        </li>
        <li class="">
            <g:render template="/_common/modals/deleteTextLink"/>
        </li>
    </g:if>

</ul>
<section id="show-principio" class="first">

	<table class="table">
		<tbody>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="principio.principio.label" default="Principio" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: principioInstance, field: "principio")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="principio.medicamento.label" default="Medicamento" /></td>
				
				<td valign="top" style="text-align: left;" class="value">
					<ul>
					<g:each in="${principioInstance.medicamento}" var="m">
						<li><g:link controller="medicamento" action="show" id="${m.id}">${m?.encodeAsHTML()}</g:link></li>
					</g:each>
					</ul>
				</td>
				
			</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>